version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
  
jobs:
  build:
    docker:
      - image: circleci/ruby:buster-browsers
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            sudo gem update --system
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - ruby/bundle-install
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Run tests
          command: bundle exec rspec specs/feedback_collection_test.rb --format documentation
